logging:
    level:
        '[org.springframework.web]': debug

spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        static-path-pattern: /resources/**
    liverload:
        enabled: true